### ISSUE TITLE
Failed to read input stream for sdkencryptedappticket64.dll

### ISSUE THREAD

**Issue by harlanhu** [code-disaster/steamworks4j#123]
Platform: Windows11 64bit
JDK: 1.8
Dependency:
```xml
<dependency>
	<groupId>com.code-disaster.steamworks4j</groupId>
	<artifactId>steamworks4j</artifactId>
	<version>1.9.0</version>
</dependency>

<dependency>
	<groupId>com.code-disaster.steamworks4j</groupId>
	<artifactId>steamworks4j-server</artifactId>
	<version>1.9.0</version>
</dependency>
```

Problem description: I try to use `SteamEncryptedAppTicket.loadLibraries();`, but it doesn't work and throws an exception `Failed to read input stream for C:\Users\xxx\AppData\Local\Temp\steamworks4j\1.9.0\sdkencryptedappticket64.dll`.
I don't have this file. How can I use it correctly?

**Comment by code-disaster** [comment]
`sdkencryptedappticket64.dll` doesn't reside in the `redistributable_bin` folder of the SDK. Since I wasn't sure about possible legal trouble, I don't include it in any "official" Maven releases of the `steamworks4j-server` package.

You can build one yourself with `mvn package -Plibs -pl server`, with the Steamworks SDK copied into a `sdk` subfolder.

I should probably document this more visibly.

**Comment by harlanhu** [comment]
Thanks for your reply,I have solved the problem.
