### ISSUE TITLE
SteamUtils.getImageRGBA leaves buffer empty

### ISSUE THREAD

**Issue by gtinon** [code-disaster/steamworks4j#18]
I have been using your library for some time and it works great, thanks!

I am trying to integrate with Steam leaderboards and everything works smoothly except getting user avatars. Here is the code I use:
```java
int imageId = Steam.friends.getSmallFriendAvatar(steamID);
int imageWidth = Steam.utils.getImageWidth(imageId);
int imageHeight = Steam.utils.getImageHeight(imageId);
int sizeInBytes = imageWidth * imageHeight * 4;

byte[] content = new byte[sizeInBytes];
ByteBuffer buffer = ByteBuffer.wrap(content);
boolean ok = Steam.utils.getImageRGBA(imageId, buffer, sizeInBytes);
```
steamID is my Steam ID or that of a Steam friend so I know there is something associated with it and I can access it.
`getSmallFriendAvatar()` returns an int > 0
`getImageWidth()` => 32
`getImageHeight()` => 32
But `buffer` remains full of 0s...

Am I missing something?

**Comment by code-disaster** [comment]
You are right. The same happens in SteamClientAPITestApp - I missed to check the image content. 

The reason is that the image buffer must be a direct buffer, e.g. created using ByteBuffer.allocateDirect().

Interestingly it doesn't crash immediately, when passed a buffer pointing to the Java heap, as it did in other places. I'll add a check for that.

**Comment by gtinon** [comment]
Thanks for the quick answer!
And that solved my problem :)
