### ISSUE TITLE
SteamUGCCallback onSubscribeItem() and onUnsubscribeItem() not called

### ISSUE THREAD

**Issue by grizeldi** [code-disaster/steamworks4j#42]
Khm. Unless I again understand steamworks' docs wrong, those methods are supposed to be called when the user subscribes to an item externally while the game is running (via steam client, steam overlay web browser, etc.). Or are these methods only supposed to be called when I subscribe with my code? According to the steamworks' docs, those methods are actually supposed to be in SteamRemoteStorageCallback, but I agree that they make more sense where they are.
I put some printlns in there and nothing gets called.

**Comment by code-disaster** [comment]
> those methods are supposed to be called when the user subscribes to an item externally while the game is running

Actually, according to the documentation, it's supposed to trigger a `RemoteStoragePublishedFile(Un-)Subscribed` callback. Good point though - those callbacks are missing.

`on(Un-)SubscribeItem()` callbacks only happen as a result of UGC function calls.

> those methods are actually supposed to be in SteamRemoteStorageCallback

Note that there are two different Workshop implementations. The one in RemoteStorage is deprecated. That information is hidden in the "Sharing User Generated Content / Technical Topics" section in the Steamworks documentation.

It would have been weird to add callbacks of UGC functions to the RemoteStorage callback adapter, only because Valve decided to reuse an existing data structure. And it would break the interface+callback scheme of the Java API.

**Comment by grizeldi** [comment]
Well it would be great if those callbacks could be added, I don't really
care to which callback interface.

Currently I have a workaround set, that I query number of subscribed items
in the game loop and execute some code if it changes. Having those
callbacks would simplify things a bit.

Thanks for the great library btw.

**Comment by code-disaster** [comment]
Hi,

changes are done, but not yet tested.

I added Travis CI support which now deploys snapshots (currently 1.6.3-SNAPSHOT) to [oss.sonatype.org/content/repositories/snapshots/](https://oss.sonatype.org/content/repositories/snapshots/). Would be cool if you can give it a try.

**Comment by grizeldi** [comment]
Sure, will try. Thanks!
