### ISSUE TITLE
add new functionalities / future plans

### ISSUE THREAD

**Issue by titoasty** [code-disaster/steamworks4j#6]
Hi,

I was wondering what are your plans about adding new functions ?
I know that you only wrote what you needed, but I think it would be very useful to integrate more api stuffs.
I saw that franzbischoff forked the project and added game server functions, don't know what are his plans about pulling its fork to this one.
Also, I could help to add new functionalites, no problem, the only problem is that I'm under linux and so I can't compile the library for macos and windows.
But anyway, tell me your plans (franzbischoff if you read this, you are welcome :)) and if I can help, I'm ready !

**Comment by code-disaster** [comment]
My grand plan is to add functions / interfaces which are tried and used contemporary, instead of bulk-adding everything which is exposed by the Steamworks API.

You are invited to fork the project and add new functions. It'd be helpful if you get into contact first about what you want to add, so that we don't have people working on the same functionality.

I'm in contact with @franzbischoff. It's definitely planned to merge his changes back when he's done.

Compiling for other platforms isn't an issue. I don't mind doing that when merging the changes eventually. Ideally you wouldn't even need to commit binaries until then.

**Comment by titoasty** [comment]
Great, so I'll fork the project and will probably work on friends and
profile (getting lost of friends, images of avatars..)

**Comment by franzbischoff** [comment]
Hi, the server functionalities I introduced in my branch is supposed to be working already. Please let me know if there is any bug. :)

**Comment by titoasty** [comment]
Great, I'll make some tests during next days

**Comment by lucienn3** [comment]
We are currently also working on more functions when we need them. :)
Im one of the team members at JIW Games. ( Rising World on steam )
:)
Awesome what you guys are doing here :+1:

**Comment by Disturbing** [comment]
Looking to get the SteamServerAPI exposed as soon as possible.  Any plans on this?

**Comment by code-disaster** [comment]
@Disturbing just what @franzbischoff has been implemented in his fork. I plan to merge back his changes ... soon'ish (tm).

**Comment by titoasty** [comment]
did you plan a higher layer to deal with batch requests ?
I began some work on this and I could show you some of my work

**Comment by code-disaster** [comment]
I've put some thoughts into it, but made no plan yet. Ideally it wouldn't inflate the API too much, and avoid doing too many (native) memory allocations.

If done as a higher layer on top of the API, I'd probably vouch for doing it in an extra module. But feel free to share your work, I'll gladly have a look at your ideas.
