### ISSUE TITLE
Problem with libsteam_api.so.

### ISSUE THREAD

**Issue by Vasalkar** [code-disaster/steamworks4j#78]
When I try to run a Java game through terminal this appears:

> Java HotSpot(TM) Server VM warning: You have loaded library /tmp/steamworks4j/1.7.0/libsteam_api.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

**Comment by code-disaster** [comment]
Which Java/VM version do you try to run it with?

**Comment by Vasalkar** [comment]
I see it through "java -version"? If so the Java/VM version is "build 25.151-b12, mixed mode".

**Comment by code-disaster** [comment]
My guess is that you are trying to run the game with a 32-bit JVM. I dropped support for 32-bit Linux builds with v1.7.0.

**Comment by Vasalkar** [comment]
Yep, thanks btw.

**Comment by code-disaster** [comment]
Note that if you _really_ want/need to use a 32-bit build, you may be able to use a version pre-1.7.0, or compile the native library yourself.

I dropped it mostly because it's been an annoyance to keep a 32-bit Linux build environment around, while - according to the Steam Hardware Surveys - customers _using_ Steam on a 32-bit Linux are pretty much extinct.

**Comment by Vasalkar** [comment]
How to download versions previous of 1.7.0?

**Comment by code-disaster** [comment]
Through Maven, for example. https://mvnrepository.com/artifact/com.code-disaster.steamworks4j provides direct download links, too.

**Comment by Vasalkar** [comment]
Where do I download 'libsteam_api.so?
